version: '3.4'

services:
  applicationdb:
    container_name: applicationdb
    environment:
     - POSTGRES_USER = admin
     - POSTGRES_PASSWORD = admin1234
     - POSTGRES_DB = ApplicationDbContext
    restart: always
    ports:
     - "5432/5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
     - PGADMIN_DEFAULT_EMAIL = admin@aspnetrun.com
     - PGADMIN_DEFAULT_PASSWORD = admin1234,
    restart: always
    ports:
     - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  sportshub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro